aleph-im/aleph-sdk-ts

package.json
src/accounts/account.ts
src/accounts/index.ts
src/accounts/substrate.ts
src/global.ts
src/index.ts
src/messages/aggregate/get.ts
src/messages/store/publish.ts
tests/accounts/ethereum.test.ts
tests/accounts/solana.test.ts
tests/index.ts
tests/messages/aggregate/get.test.ts
tests/messages/aggregate/publish.test.ts
tests/messages/post/publish.test.ts
tests/messages/store/get.test.ts
testsAuto/accounts/index.ts
testsAuto/accounts/substrate.auto.ts
testsAuto/entryPoint.ts
testsAuto/index.ts
yarn.lock

- Substrate account:   Generate new account - import from mnemonic, private key - sign messages.
- Jest Tests:                 Changes made on imports for all Jest's tests to allow running TestsAuto and Jest.
- TestsAuto:                 A handmade solution that allows testing substrate cause it is not suitable with the Jest framework.
- Add 2 news dependencies: `@polkadot/keyring`, `@polkadot/util-crypto` in package.json
- All methods and class's related to this change are located in `./src/accounts/substrate.ts`
- Creation of a new `index.ts` in the test dir to make jest's tests refer to these imports.
- The main diff with `index.ts` located in src is that it does not import substrate account cause it's not supported and make jest crash
- Creation of a new file called `global.ts` in src …

Add substrate account implementation

---

src/accounts/avalanche.ts
tests/accounts/avalanche.test.ts

Switched to default base58 encoding for avalanche issued message.
A [test case](https://github.com/aleph-im/aleph-sdk-ts/blob/quickfix-ava-cb58/tests/accounts/avalanche.test.ts#L53) was written to ensure compatibility.

Fix hex avalanche message not being posted

---

src/accounts/account.ts
src/accounts/avalanche.ts
src/accounts/ethereum.ts
src/accounts/nuls.ts
src/accounts/nuls2.ts
src/accounts/solana.ts
src/accounts/substrate.ts
tests/accounts/avalanche.test.ts
tests/accounts/ethereum.test.ts
tests/accounts/nuls.test.ts
tests/accounts/nuls2.test.ts
tests/accounts/solana.test.ts
testsAuto/accounts/substrate.auto.ts

The public key is only used on some chains. A side effect from this premature optimization is that it cannot be obtained from a web3 provider.
Remove the public key from the parent Account class and derive it when needed on specific chains.

Remove public key from the Account class

---

package.json
tests/messages/forget/publish.test.ts

Forget message structure has been updated in Aleph client

Fix forget message testing (due to API changes)

---

src/accounts/solana.ts
tests/accounts/solana.test.ts
tests/provider/solanaProvider.ts

Updating signMessage methods with a provider, to support phantom and solana-labs/wallet-adapter format

Add Solana 'wallet-adapter' support

---

src/messages/create/publish.ts
src/messages/message.ts
tests/accounts/ethereum.test.ts

Make `item_content` = null rather than an empty string to avoid 422 error status.

Fix non-inline message

---

src/messages/aggregate/get.ts
src/messages/create/publish.ts
src/messages/create/signature.ts
src/messages/post/get.ts
src/messages/store/get.ts
src/utils/url.ts

If the SDK is called from a VM with the `ALEPH_API_UNIX_SOCKET` env variable set, all the request to the API will be proxied via the provided socket.
closes #35

Add support for request proxying via CRN host

---

.github/workflows/publish.yaml

This Github action will deploy the new package version when it detects a commit in the format `Release [version]` and if the package.json version has changed. It will also create a git tag accordingly

feat: Add a github action to publish

---

package.json

Reverts aleph-im/aleph-sdk-ts#84
Does not work as root imports are undocumented

Revert "doc: Do not generate docs for internal use helpers"

---

tests/messages/aggregate/get.test.ts
tests/messages/aggregate/publish.test.ts

Solution: Make the test's account from get aggregate random

Patch: protect aggregate test from alteration

---

src/messages/aggregate/get.ts
src/messages/post/get.ts
tests/messages/aggregate/get.test.ts
tests/messages/aggregate/publish.test.ts

Fetching aggregates without a limit parameter could return a 500 error under certain circumstances. 
Solution: Adding a hard limit to 50 in the SDK (while still adding a `limit` parameter for end user to increase it if needed)

Patch aggregate queries

---

src/messages/aggregate/publish.ts
tests/messages/aggregate/update.test.ts

Feat: User was not able to use the Security key feature from aggregate
Solution: Add an optional field to update aggregate for another user.
Usage on python: https://aleph-im.gitbook.io/aleph-client/api-resources-reference/aggregates/security-key
https://github.com/aleph-im/aleph-client/blob/5e7c2bd6003e028e427a895d0f6bd1559dbb2e5d/src/aleph_client/asynchronous.py#L205

Add delegate update for aggregate message

---

src/messages/post/get.ts
tests/messages/post/get.test.ts

Feat: User can't specify channels for post fetching like in the Python SDK
Solution: Add an optional field for channel in get post.

Add Channels field for getting post message

---

README.md
examples/toolshed/src/components/SelectProvider.tsx
examples/toolshed/src/components/WalletConfig.tsx
examples/toolshed/src/model/chains.ts
src/accounts/avalanche.ts
src/providers/JsonRPCWallet.ts
tests/accounts/avalanche.test.ts
tests/providers/ethereumProvider.ts

Add metamask support and tests
related issue: https://github.com/aleph-im/aleph-sdk-ts/issues/60

Add provider for Avalanche Account

---

src/messages/forget/index.ts
src/messages/forget/publish.ts
tests/messages/forget/publish.test.ts

All other Publish methods start with a capital letter

Chore (minor): Forget Publish method wasn't capitalized

---

src/index.ts
src/messages/index.ts

Typedoc wasn't working properly with the previous namespace export, should work now.

Messages export is not recognized properly by typedoc

---

src/messages/post/get.ts
src/messages/store/get.ts
tests/messages/post/get.test.ts
tests/messages/store/get.test.ts

The goal is to enhance user experience by providing reasonable default arguments to the GET method. Previously, user had to manually provide empty arrays to ignore field in the message lookup. Also added the default API url as a default argument

Add default parameters to GET (post, aggregates, store)

---

package-lock.json
src/accounts/account.ts
src/accounts/avalanche.ts
src/accounts/ethereum.ts
src/accounts/nuls2.ts
tests/accounts/avalanche.test.ts
tests/accounts/eciesAccount.test.ts
tests/accounts/ethereum.test.ts
tests/accounts/nuls2.test.ts

Solution: Add an optional field for already existing encrypt() to target another account.
Linked to: https://github.com/aleph-im/aleph-sdk-ts/issues/95

Feat: User can't sign data for another account or public key

---

package.json
src/accounts/providers/Ledger/ethereum.ts

ETH Ledger app is currently in 1.10.9 and was detected as lower than 1.9.0 by the SDK.

Fix: semver checking issue with ledger application for eth.

---

examples/toolshed/src/components/WalletConfig.tsx
src/accounts/avalanche.ts
src/accounts/ethereum.ts
src/accounts/providers/JsonRPCWallet.ts

Users could not choose a custom RPC enpoint with web3 providers
This Feature mainly concerns Metamask's users to avoid data collection with the Infura default endpoint.
Even if the data collection is done during a transaction, some people probably want to initiate their connection with another more secure endpoint.

Allow to choose RPC endpoint with Web3 Provider

---

.github/workflows/publish.yaml

This github action should publish a package on both the NPM and Github registry when a new release is created.
Reference: 
https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

Add a Github action to publish packages upon release

---

src/accounts/account.ts
src/accounts/avalanche.ts
src/accounts/ethereum.ts
src/accounts/nuls2.ts

Refers to this issue: https://github.com/aleph-im/aleph-sdk-ts/issues/124
This implementation might cause a breaking change, as the publicKey from ECIESAccount can be `undefined`.
- Add a new  `abstract askPubKey(): Promise<void>;` inside ECIESAccount. This method can be called manually or be triggered inside the `encrypt` method.
- If a pubKey is already instanced nothing will happened when call askPubKey();
- Encrypt() will automatically call askPubKey() if an encryption for a tier is required

Fix: Ask for the encryption pubKey only at the encryption time

---

examples/toolshed/src/components/SelectProvider.tsx
examples/toolshed/src/components/WalletConfig.tsx
src/accounts/providers/JsonRPCWallet.ts

- Add Polygon and Binance smart chain to the default Rpc endpoints list.
- Add a way to test in Toolshade protocols or endpoint swap:
- Choose `Ethereum (Metamask)`
- Pick the wrapped protocol of your choice
- click on `connect provider`
Any other protocol relying on the ETH signature can be added by passing a custom RPC endpoint when initializing an Eth account.

Feat: Add wrapped protocol implementation for Matic and BSC

---

examples/stake-on-me/cli.ts
examples/toolshed/package-lock.json
examples/toolshed/package.json
examples/toolshed/src/App.tsx
examples/toolshed/src/components/EncryptionConfig.tsx
examples/toolshed/src/components/HardwareConfig.tsx
examples/toolshed/src/components/KeypairConfig.tsx
examples/toolshed/src/components/MessageConfig.tsx
examples/toolshed/src/components/SelectProvider.tsx
examples/toolshed/src/components/WalletConfig.tsx
examples/toolshed/src/reducer.ts
examples/toolshed/vite.config.ts
package-lock.json
package.json
src/accounts/account.ts
src/accounts/avalanche.ts
src/accounts/ethereum.ts
src/accounts/nuls2.ts
src/accounts/providers/BaseProviderWallet.ts
src/accounts/providers/JsonRPCWallet.ts
src/accounts/providers/ProviderEncryptionLib.ts
tests/accounts/avalanche.test.ts
tests/accounts/cosmos.test.ts
tests/accounts/ethereum.test.ts
tests/accounts/nuls2.test.ts
tests/accounts/solana.test.ts
tests/accounts/tezos.test.ts
tests/messages/aggregate/update.test.ts
tests/providers/ethereumProvider.ts
testsAuto/accounts/substrate.auto.ts

Related to: https://github.com/aleph-im/aleph-sdk-ts/issues/114
Working on implementation specifically [for metamask](https://docs.metamask.io/guide/rpc-api.html#unrestricted-methods).
As this feature was already implemented in the SDK, I think finishing the implementation can make sense here.
Besides this fix, this PR will also add a new feature to allow encryption testing inside the Toolshed. 
Be aware of the potential [security issue](https://medium.com/metamask/metamask-api-method-deprecation-2b0564a84686) using this method.
This PR introduce the decrypt function inside ECIESAccount:
`abstract decrypt(content: Buffer): Promise<Buffer>;`
This means the NULS2 `decrypt() `function needs to wait from now.

Fix: Message can't be encrypted with ethereum web3 provider

---

src/messages/any/getMessage.ts
src/messages/any/getMessages.ts
tests/messages/any/get.test.tsx

A query with no results is an acceptable response. If any.GetMessages has no match it still returns an empty array. It is up to the user to handle rejection (.... or not).

fix: getMessages now fails silently

---

package-lock.json
package.json
src/messages/store/publish.ts
src/messages/store/utils.ts

SDK implementations of  : https://github.com/aleph-im/pyaleph/pull/463

Feature: Secure upload mechanism

---

src/messages/aggregate/get.ts
tests/messages/aggregate/get.test.ts

The API does not seem to allow fetching multiple **keys** for an AGGREGATE message. However, fetching a single works fine. This PR replaces the `keys: string[]` parameter with a `key: string` (singular) to match the API.

Fix : Cannot fetch multiple aggregate keys? 

---

examples/toolshed/src/components/SelectProvider.tsx
examples/toolshed/src/components/WalletConfig.tsx
examples/toolshed/src/model/chains.ts
package-lock.json
package.json
src/accounts/substrate.ts
src/messages/any/getMessagesSocket.ts
tests/accounts/cosmos.test.ts
tests/accounts/ethereum.test.ts
tests/accounts/solana.test.ts
tests/accounts/tezos.test.ts
tests/providers/ethereumProvider.ts

Feat: Providers are not handled by Substrate account
Solution: Add Polka.js support
(related to: https://github.com/aleph-im/aleph-sdk-ts/issues/60)
- At this moment, the Aleph network won't be able to validate messages from provided Dot Account, until nodes upgrade their dependency `substrateinterface`
- This feature is not tested, because it can only be run in the browser and it doesn't appear to have any documented tool for mocking polkadotjs extension.
Link to the PyAleph PR: https://github.com/aleph-im/pyaleph/pull/358
- I modify a local Aleph node with `substrateinterface` in 1.4.1
- The Sign() method of Substrate have a new verification step to check the integrity of the signature using `signatureVerify()`
- Make some manuals tests with toolshed
- …

Add Polkajs provider for Substrate

---

packages/core/src/utils.ts
packages/message/src/instance/impl.ts
packages/message/src/utils/constants.ts

Following this function from aleph-message: https://github.com/aleph-im/aleph-message/blob/main/aleph_message/utils.py#L11

Limit rootfs size to not trigger message rejection

---

README.md
packages/account/README.md
packages/account/package.json
packages/account/src/account.ts
packages/avalanche/README.md
packages/avalanche/package.json
packages/client/README.md
packages/client/package.json
packages/core/README.md
packages/core/package.json
packages/cosmos/README.md
packages/cosmos/package.json
packages/ethereum-ledger/README.md
packages/ethereum-ledger/package.json
packages/ethereum/README.md
packages/ethereum/package.json
packages/evm/README.md
packages/evm/package.json
packages/message/README.md
packages/message/package.json
packages/nuls2/README.md
packages/nuls2/package.json
packages/solana/README.md
packages/solana/package.json
packages/substrate/README.md
packages/substrate/package.json
packages/superfluid/README.md
packages/superfluid/package.json
packages/tezos/README.md
packages/tezos/package.json

All packages now have descriptions of their contents and link back to the official docs and the @aleph-sdk/client NPM site.

Update and add README.md where needed for v1.0.0 release

---

package.json
packages/core/src/constants.ts
packages/dns/README.md
packages/dns/__tests__/domain.test.ts
packages/dns/package.json
packages/dns/src/constants.ts
packages/dns/src/domain.ts
packages/dns/src/errors.ts
packages/dns/src/index.ts
packages/dns/src/types.ts
packages/superfluid/src/account.ts
packages/superfluid/src/constants.ts
packages/superfluid/src/index.ts
rollup.config.js

Build fails due to polyfill not possible on `dns` Node.js module.

Add DNS functionality

---

packages/message/__tests__/store/publish.test.ts
packages/message/src/store/impl.ts
packages/message/src/store/types.ts

This pull request introduces the ability to include extra fields in Store messages, further bridging the gap between the Python and TS SDKs. 
It addresses and resolves #171.

Feature: Add Extra Fields to Store Messages

---

packages/message/src/aggregate/impl.ts

fix(message/aggregate): Remove keys query param when no value is passed

---

packages/message/src/forget/impl.ts
packages/message/src/forget/types.ts
packages/message/src/post/impl.ts

Didn't tested locally but looks pretty straight forward

feat(message): Parameter added to FORGET a message sent through the permission system

---

README.md

Added support for Deno v2.
Tested while implementing [Twentysix-Claim's backend](https://github.com/aleph-im/twentysix-claim/tree/master/backend).

Add deno v2 support
